site_name: Flagrantes
theme:
  language: pt-BR
  name: 'material'
  palette:
    # Palette toggle for dark mode
    - scheme: slate
      primary: teal 
      accent: black
      toggle:
        icon: material/weather-night
        name: Modo Noturno
  
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/weather-sunny
        name: Modo Claro
features:
    - toc.integrate     
markdown_extensions:
    - pymdownx.tasklist: #lista de tarefas
        custom_checkbox: true
        clickable_checkbox: true
    - pymdownx.emoji:
        emoji_index: !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:materialx.emoji.to_svg
    - pymdownx.mark
    - pymdownx.tilde
    - pymdownx.highlight
    - admonition
    - pymdownx.details
    - pymdownx.superfences:
        custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format
    - attr_list
    - tables
    - pymdownx.tabbed:
        alternate_style: true 
#site_url: https://example.com/
nav:
    - Tráfico: index.md
    - Violência Doméstica: about.md
    - Perguntas Frequentes: perguntas.md
theme: material #readthedocs
    

extra_css:
  - stylesheets/dark_theme.css
  - stylesheets/codehilite.css
  - https://unpkg.com/mermaid@8.5.1/dist/mermaid.css
extra_javascript:
  - https://unpkg.com/mermaid@8.5.1/dist/mermaid.min.js